#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from mixs
import mixs
from mixs.lib import clean_data

if __name__ == '__main__':
    pass
